/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tk.kodlamasi;

import javax.swing.JOptionPane;

/**
 *
 * @author www.KODLAMASI.tk
 */
public class KahvePRO_GUI extends javax.swing.JFrame {

    /**
     * Creates new form KahvePRO_GUI
     */
    public KahvePRO_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bttn_pisir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmb_box_kahve_turu = new javax.swing.JComboBox();
        cmb_box_seker_sayisi = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_area_kahveler = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        txtfd_kahveLimiti = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lbl_bilgi = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(111, 104, 93));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "KAHVECİ FEYMİ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Purisa", 1, 18), new java.awt.Color(241, 147, 14))); // NOI18N

        bttn_pisir.setText("Pişir");
        bttn_pisir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_pisirActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 171, 21));
        jLabel1.setForeground(new java.awt.Color(74, 71, 59));
        jLabel1.setText("Kahve Türü");
        jLabel1.setOpaque(true);

        jLabel2.setBackground(new java.awt.Color(249, 161, 2));
        jLabel2.setText("Şeker Sayisi");
        jLabel2.setOpaque(true);

        cmb_box_kahve_turu.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Türk Kahvesi", "Java Kahvesi", "Nescafe" }));

        cmb_box_seker_sayisi.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4" }));

        txt_area_kahveler.setColumns(20);
        txt_area_kahveler.setRows(5);
        jScrollPane1.setViewportView(txt_area_kahveler);

        jLabel3.setBackground(new java.awt.Color(255, 164, 0));
        jLabel3.setText("KahveLimiti:");
        jLabel3.setOpaque(true);

        txtfd_kahveLimiti.setText("5");

        jLabel4.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 156, 0));
        jLabel4.setText("Bilgi:");

        lbl_bilgi.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        lbl_bilgi.setForeground(new java.awt.Color(255, 156, 0));
        lbl_bilgi.setText("...");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(bttn_pisir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmb_box_seker_sayisi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmb_box_kahve_turu, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtfd_kahveLimiti, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_bilgi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_box_kahve_turu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(txtfd_kahveLimiti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmb_box_seker_sayisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(lbl_bilgi))
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(bttn_pisir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public int kahve_no =1;//PİŞİRME SAYISINI TUTMAK İÇİN - HER YENİKAHVE İÇİN İD NOSU BELİRLEMEYİ SAĞLAR
    private void bttn_pisirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_pisirActionPerformed
        String turu =String.valueOf(cmb_box_kahve_turu.getSelectedItem() );
        int seker =Integer.parseInt(cmb_box_seker_sayisi.getSelectedItem().toString() );
        int limit =Integer.parseInt(txtfd_kahveLimiti.getText());
        if(kahve_no==limit)
        {
            JOptionPane.showMessageDialog(rootPane,"Devam etmek için Limiti Arttırın", "Kahve Limiti Doldu", 2);
            lbl_bilgi.setText("Limit Doldu.\nDevam Etmek İçin Arttırın");
        }else{
        Kahve yenikahve[] = new Kahve[limit];
        yenikahve[kahve_no]=new  Kahve(turu, seker);
        
        txt_area_kahveler.append(""+kahve_no+"-Kahvenin adı: "+yenikahve[kahve_no].getKahve_Adi()+
                                " Şeker Sayısı:"+yenikahve[kahve_no].getSeker_sayisi()+"\n");
        kahve_no++;
        }
    }//GEN-LAST:event_bttn_pisirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KahvePRO_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KahvePRO_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KahvePRO_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KahvePRO_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KahvePRO_GUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttn_pisir;
    private javax.swing.JComboBox cmb_box_kahve_turu;
    private javax.swing.JComboBox cmb_box_seker_sayisi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_bilgi;
    private javax.swing.JTextArea txt_area_kahveler;
    private javax.swing.JTextField txtfd_kahveLimiti;
    // End of variables declaration//GEN-END:variables
}
